"""rbac_redesign

Revision ID: ca976804124b
Revises: 3b03867098e4
Create Date: 2026-07-13 17:17:09.269943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca976804124b'
down_revision = '3b03867098e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignments', sa.Column('marks_obtained', sa.Float(), nullable=True))
    op.add_column('assignments', sa.Column('max_marks', sa.Float(), nullable=True))
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subjects', 'users', ['teacher_id'], ['id'], ondelete='SET NULL')
    op.add_column('timetable', sa.Column('faculty_name', sa.String(), nullable=True))
    op.add_column('timetable', sa.Column('building', sa.String(), nullable=True))
    op.add_column('timetable', sa.Column('class_type', sa.String(), nullable=False))
    op.add_column('timetable', sa.Column('recurrence', sa.String(), nullable=False))
    op.add_column('timetable', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('timetable', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('timetable', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    
    # Rename hashed_password to password_hash
    op.alter_column('users', 'hashed_password', new_column_name='password_hash')
    # Alter student_id to be nullable
    op.alter_column('users', 'student_id', nullable=True)
    
    op.add_column('users', sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'TEACHER', 'STUDENT', name='userrole'), nullable=False, server_default='STUDENT'))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'RETIRED', name='userstatus'), nullable=False, server_default='ACTIVE'))
    op.add_column('users', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(), nullable=True))
    op.add_column('users', sa.Column('roll_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('semester', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('section', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_roll_number'), 'users', ['roll_number'], unique=True)
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_roll_number'), table_name='users')
    op.drop_column('users', 'section')
    op.drop_column('users', 'semester')
    op.drop_column('users', 'roll_number')
    op.drop_column('users', 'designation')
    op.drop_column('users', 'department')
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role')
    
    # Restore student_id nullability and rename password_hash back
    op.alter_column('users', 'student_id', nullable=False)
    op.alter_column('users', 'password_hash', new_column_name='hashed_password')
    
    op.drop_column('timetable', 'updated_at')
    op.drop_column('timetable', 'is_active')
    op.drop_column('timetable', 'notes')
    op.drop_column('timetable', 'recurrence')
    op.drop_column('timetable', 'class_type')
    op.drop_column('timetable', 'building')
    op.drop_column('timetable', 'faculty_name')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_column('subjects', 'teacher_id')
    op.drop_column('assignments', 'max_marks')
    op.drop_column('assignments', 'marks_obtained')
    # ### end Alembic commands ###
