"""add_phase4_erp_tables_v2

Revision ID: e82e6751938b
Revises: ca976804124b
Create Date: 2026-07-13 18:34:36.003187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82e6751938b'
down_revision = 'ca976804124b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_announcements_id'), 'announcements', ['id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('quiz', sa.Float(), nullable=True),
    sa.Column('assignment', sa.Float(), nullable=True),
    sa.Column('lab', sa.Float(), nullable=True),
    sa.Column('internal', sa.Float(), nullable=True),
    sa.Column('mid_exam', sa.Float(), nullable=True),
    sa.Column('practical', sa.Float(), nullable=True),
    sa.Column('final', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('average', sa.Float(), nullable=True),
    sa.Column('percentage', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marks_id'), 'marks', ['id'], unique=False)
    op.add_column('notes', sa.Column('unit', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('topic', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('file_type', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('subjects', sa.Column('department', sa.String(), nullable=True))
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('batch', sa.String(), nullable=True))
    op.add_column('users', sa.Column('admission_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('parent_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('parent_phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('guardian', sa.String(), nullable=True))
    op.add_column('users', sa.Column('photo', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_admission_number'), 'users', ['admission_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_admission_number'), table_name='users')
    op.drop_column('users', 'photo')
    op.drop_column('users', 'guardian')
    op.drop_column('users', 'parent_phone')
    op.drop_column('users', 'parent_name')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'admission_number')
    op.drop_column('users', 'batch')
    op.drop_column('users', 'year')
    op.drop_column('subjects', 'department')
    op.drop_column('notes', 'file_url')
    op.drop_column('notes', 'file_type')
    op.drop_column('notes', 'topic')
    op.drop_column('notes', 'unit')
    op.drop_index(op.f('ix_marks_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index(op.f('ix_announcements_id'), table_name='announcements')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
